language: csharp
solution: TvShowReminder.sln
install:
  - nuget restore TvShowReminder.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release TvShowReminder.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./TvShowReminder.Unittests/bin/Release/TvShowReminder.Unittests.dll
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./TTvShowReminder.TvMazeApi.UnitTests/bin/Release/TvShowReminder.TvMazeApi.UnitTests.dll